WIP Add AtomicFolder
untitaker/python-atomicwrites pull request #36
Opened 2018-08-12 09:00 UTC by sotte

This is pretty much just copy&paste from one of my projects. Your version is much more sophisticated but I think it's good to have the code just to get the discussion started.

Things that have to be addressed:
- [ ] `rename_dont_move` could be replaced by existing functionality.
- [ ] Test on windows.
- [ ] Adjust coding style
- [ ] Update docs
- [ ] Write tests
- [ ] Anything else?

@untitaker what do you think?

I'll clean up the commit history once the PR is ready.

This PR closes #35.

2018-08-12 09:23 UTC, untitaker requested changes
Regarding codestyle, I will eventually run [black](https://github.com/ambv/black) against the entire codebase, so don't worry too much about it.

2018-08-12 09:23 UTC, untitaker commented on atomicwrites/__init__.py
> +###############################################################################
If this is necessary I think it's time to start a new file! Please create a file `folders.py` and import `AtomicFolder` from it.

2018-08-12 09:23 UTC, untitaker commented on atomicwrites/__init__.py
> +    shutil.move(path, dst)
This function is not atomic as the implementation in luigi notes in its warning message. Here is a race condition for example: We have two processes A and B, which both run this function.

* Process A runs `isdir`, which returns false
* Process B runs `isdir`, which returns false
* Process A moves its tmpdir to the target path
* Process B moves its tmpdir to the target path (or rather, *into* the directory created by A)

I am not sure whether we can guarantee to fail atomically if the target path doesn't exist. If you have any ideas regarding that... Ideally we would have an `overwrite` param but I am not sure if that is possible.

2018-08-12 09:23 UTC, untitaker commented on atomicwrites/__init__.py
> +class AtomicFolder():
Please model `AtomicFolder` like the API of `AtomicWriter` for consistency, concretely that it itself is not a contextmanager but rather has a `open()` method that returns a context manager, and separate methods for `commit` and `rollback`.

2018-08-12 09:25 UTC, untitaker commented on atomicwrites/__init__.py
> +class AtomicFolder():
Oh and please subclass from `object` such that we have a newstyle class on both Python 2 and 3.

2018-08-12 09:42 UTC, sotte commented on atomicwrites/__init__.py
> +###############################################################################
Sure, I'll do that once the content is fine!

2018-12-16 18:32 UTC, untitaker commented
See discussion on #35

2018-12-16 18:32 UTC, closed without merging